{% raw -%}
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10.0-rc.3"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: lint-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            lint-pip-${{ matrix.python-version }}-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.2.0a2
          poetry install
{%- endraw %}
      - name: Lint Python
        run: make lint

      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v1
