{% raw -%}
name: Lint

on:
  push:
    branches: [master, main]

  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: lint-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            lint-pip-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name: Lint
        run: make lint
{%- endraw %}
