{% raw -%}
name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install

      - name: Publish to PyPI
        run: make publish
        env:
          POETRY_PYPI_TOKEN_PYPI: "${{ secrets.PYPI_TOKEN }}"
{%- endraw -%}
