name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  template:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.7", "pypy-3.8"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: lint-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            lint-pip-${{ matrix.python-version }}-

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Cookiecutter
        run: |
          python -m pip install --upgrade cookiecutter

      - name: Run Cookiecutter
        run: cookiecutter . --no-input

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
        working-directory: "package-name"

      - name: Run tests
        run: tox
        working-directory: "package-name"
