name: Rename and execute Copier

on: [push]

permissions: write-all

jobs:
  rename-and-copy-project:
    if: ${{ !contains(github.repository, '/python-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Rename and Copy Project with Copier
        if: steps.is_template.outputs.is_template == 'true'
        run: |
          echo "Running Copier with -n(name) ${{ env.REPOSITORY_NAME }} -u(urlname) ${{ env.REPOSITORY_URLNAME }}"
          copier copy . . --trust --data project_name=${{ env.REPOSITORY_NAME }} --data description="Awesome ${{ env.REPOSITORY_NAME }} created by ${{ env.REPOSITORY_OWNER }}" --data full_name=${{ env.REPOSITORY_OWNER }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "✅ Ready to clone and code."
          push_options: --force
